### PR TITLE
Update status history sidebar styling DAH-37

### PR DESCRIPTION
**Pull request by akegan**
This PR updates the status history header to match styling for h3 in the figma designs for DAH-37

Before:
image

After:
image

### CODE REVIEW

**Comment by akegan** [comment]
I'd also be up for doing this with utility classes too, or getting rid of this style all together and updating the app-card_h3 styling to match what's expected here.

**Comment by akegan** [comment]
@james-wills-sf oops we forgot to merge this one in. The styling is already in partners because I pulled it into one of the PRs today.  Still have question from above though

**Comment by akegan** [comment]
@james-wills-sf Oh, I didn't realize that the styling changes in the design from when it's a sidebar to when it's below. It goes from matching h3 to matching h2. I'll go back to the drawing board.

**Comment by james-wills-sf** [comment]
@akegan maybe it makes more sense for at medium and below we hide the h3 and we just wrap the whole sidebar in a content container with a title?

That way we can also apply consistent padding without having to use the one-off padding I added

**Comment by akegan** [comment]
that could make sense too!

**Comment by akegan** [comment]
@james-wills-sf I've updated this PR to remove the label examples and the sidebar html tables

**Review by james-wills-sf — APPROVED** [review]
@akegan lgtm!

**Pull request merged**
