### PR TITLE
[PatternLibrary] Add indeterminate checkbox style [DAH-564]

### PR DESCRIPTION
**Pull request by james-wills-sf**
[DAH-564]

- 2020-11-23 at 12 36 12 PM

I think we should follow a pattern like: https://www.peanutbutterjavascript.com/how-to-build-an-indeterminate-checkbox-in-react/ for the react implementation. We could also just add an `.indeterminate` class if that doesn't work, but I'd rather we use the official html attrs for it.

[DAH-564]: https://sfgovdt.jira.com/browse/DAH-564

### CODE REVIEW

**Comment by akegan** [comment]
is it just me or does it look like it's slightly off center to the left? It also looks a touch wide to me but I'm not sure

**Comment by james-wills-sf** [comment]
@akegan it was off to the left. Updated to fix that. I think the designs have it look super wide too

designs
- 2020-11-23 at 12 47 29 PM

pattern library
- 2020-11-23 at 12 47 33 PM

**Comment by akegan** [comment]
looks like it isn't working on chrome in this PR either 
image

**Comment by akegan** [comment]
actually it looks like I just had to restart my local server, one sec

**Review by akegan — APPROVED** [review]

**Pull request merged**
